services:
  db:
    container_name: gibdd_db
    image: postgres:13-alpine3.14
    environment:
      POSTGRES_DB: gibdd
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./../docker/volumes/gibdd_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    container_name: gibdd
    image: gibdd
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"