server:
  servlet:
    context-path: /number
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://gibdd_db:5432/gibdd
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
logging:
  level:
    org.springframework:
        jdbc:
          core:
            JdbcTemplate: debug
springdoc:
  api-docs:
    path: /api-docs

